language: node_js
node_js:
  - "8"
cache: yarn
script:
  - npm test
  - npm run build
after_success: find dist -type f -exec curl -3 --ftp-create-dirs -T {} ftp://$FTP_USER:$FTP_PASSWORD@ftp.carehr.nl/public_html/in-uit/ \;
