language: node_js
node_js:
  - '10'
script:
  - npm test
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: HOFJFa+r2OFQyZP1ydz8PxuRli/WdCpdHyKwRoPuBQ7XKTuzOtQOgJDsDNn7fiAlbRDtiamqJbgjku84dh/iXTyVj1+ZN7iQldERBtvGPW/e2frPGXOwL0OtYbtBrKjzSJpoN4wXGOa7K4tZIUsiIAlogkKOhWRKxKEEwSVQqJrLJcOAWdWbKD7H6dfb73BP3WCQmtG+CT72UQb64ZM6D23KA7A242vSGOKPkrt1TdpeTHflCAG3lQXjRLwGy6SaZrAUJtcf2PU563HtQ+2aUYwIVfgnupjNKf5CZWg4qyGdn1y45cOJ0hGnRfm87nsYQA+/zjWRTthc2pb1C3HW3UFB1osaL332WN+GJJXAyyi/LxfdB4gsbxpZ1rzSXcbxzjjPk3Aoir8Pup7Ump+qUixqUQbBva5+flLcGKwKZs4nXa/eYE50bYlDrFLljtSWrieIoJxl8Evc99I6NQf9yaauGjDLLnMQ7tPpdilP9QHUI2FuYoWaND4T/I8v1UiecZeguezkfXO9V35qkboT+ZdqX1FpcB+Ti7IJgP+BN7FRHqeKkOh3C9phe2zr7zkcUp8fn3i2wTIGinsBrgZf9xdKyQd1NxooCh+2koy/fKcCp+VZkZ/4Dfb14Tj9M0pLCubfmbAeQGEHHO9ioFkICuhyycZuO6T2WHMDKJO7UWI=
