language: node_js
node_js:
  - "8"
before_install:
  - npm config set @fortawesome:registry https://npm.fontawesome.com/$FONTAWESOME_NPM_TOKEN
script:
  - npm test
  - npm run build
after_success:
  - "cd dist; zip -r ../income-expenses.zip *; cd .."
  - "curl -F 'data=@income-expenses.zip' -H 'X-Key: '$DEPLOY_KEY -H 'X-ExtractTo: in-uit' https://carehr.nl/deploy/"
