-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.items
(
    id character varying COLLATE pg_catalog."default" NOT NULL,
    amount double precision NOT NULL DEFAULT '0'::double precision,
    checked boolean NOT NULL DEFAULT false,
    category character varying COLLATE pg_catalog."default" NOT NULL,
    responsible character varying COLLATE pg_catalog."default" NOT NULL,
    type character varying COLLATE pg_catalog."default" NOT NULL,
    title character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT items_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.items
    OWNER to postgres;

GRANT ALL ON TABLE public.items TO anon;

GRANT ALL ON TABLE public.items TO authenticated;

GRANT ALL ON TABLE public.items TO postgres;

GRANT ALL ON TABLE public.items TO service_role;

COMMENT ON TABLE public.items
    IS 'Incomes and expenses';
